---
- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    name: "*"
    state: present
    update_cache: true

- name: Add Docker's APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/debian bookworm stable
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name: docker
    state: present
    update_cache: true

- name: Install Docker Compose
  ansible.builtin.apt:
    name: docker-compose
    state: present
    update_cache: true

- name: Run whoami without become.
  ansible.builtin.command: whoami
  changed_when: false
  become: false
  register: whoami

- name: Set a fact with the user name.
  ansible.builtin.set_fact:
    login_user: "{{ whoami.stdout }}"

- name: Add the current user to 'docker' group
  become: true
  ansible.builtin.user:
    name: "{{ whoami.stdout }}"
    groups: docker
    append: true

- name: Reset SSH connection to refresh user groups
  ansible.builtin.meta: reset_connection
